"""Second migrations

Revision ID: d8f1ff1ae726
Revises: 097385585236
Create Date: 2024-07-18 00:06:03.193548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f1ff1ae726'
down_revision: Union[str, None] = '097385585236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cheese_id'), 'cheese', ['id'], unique=False)
    op.create_index(op.f('ix_cheese_type_id'), 'cheese_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheese_type_id'), table_name='cheese_type')
    op.drop_index(op.f('ix_cheese_id'), table_name='cheese')
    # ### end Alembic commands ###
